name: CI/CD

on: [push, pull_request]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --save-dev npm-run-all

      - name: Build front
        run: npm run build

      - name: Run tests with coverage
        run: npm run test

     

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run server for e2e tests
        run: npm run start &

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Check if coverage directory exists
        run: ls -R coverage

      - name: Check lcov.info content
        run: |
          echo "--- Start of lcov.info ---"
          head -n 20 coverage/lcov.info || echo "lcov.info might be empty or missing"
          echo "--- End of lcov.info snippet ---"

      - name: Coveralls report
        uses: coverallsapp/github-action@v2.3.6
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
