name: CI/CD

on: [push, pull_request]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies
        run: cd front && npm install

      - name: Fix npm dependencies issue
        run: |
          cd front
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          
      - name: Build frontend
        run: cd front && npm run build
        
      - name: Check handler.js exists
        run: test -f front/build/handler.js

      - name: Run backend tests
        run: npm test

      - name: Run server for e2e tests
        run: |
          # Obtener el puerto dinámicamente
          export SERVER_PORT=$(node -e "console.log(process.env.PORT || 16078)")
          
          # Iniciar el servidor
          npm run start &
          
          # Esperar a que el servidor esté listo
          echo "Esperando que el servidor inicie en puerto $SERVER_PORT..."
          sleep 10
          
          # Guardar el puerto para usarlo en los siguientes pasos
          echo "SERVER_PORT=$SERVER_PORT" >> $GITHUB_ENV
          
          # Verificar que el servidor responde en el puerto correcto
          npx wait-on http://localhost:$SERVER_PORT -t 30000

      - name: Install Playwright dependencies
        run: |
          npx playwright install --with-deps
          npm install -g wait-on

      - name: Run Playwright tests
        run: npx playwright test
        env:
          # Usar el puerto detectado dinámicamente
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:${{ env.SERVER_PORT }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
