name: CI/CD

on: [push, pull_request]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies
        run: cd front && npm install

      - name: Fix npm dependencies issue
        run: |
          cd front
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          
      - name: Build frontend
        run: cd front && npm run build
        
      - name: Check handler.js exists
        run: test -f front/build/handler.js

      - name: Run backend tests
        run: npm test

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
